
	IF OBJECT_ID('DBO.R_DET_PRESTAMO') IS NOT NULL DROP TABLE [dbo].[R_DET_PRESTAMO]

	CREATE TABLE [dbo].[R_DET_PRESTAMO](
		[N_CVE_PRESTAMO] [int] NOT NULL,
		[N_TIPO] [tinyint] NOT NULL,
		[N_NO_CUOTA] [tinyint] NOT NULL,
		[N_MONTO_CUOTA] [numeric](18, 2) NOT NULL,
		[D_FECHA_REGISTRO] [datetime] NULL,
		[C_ESTATUS] [varchar](2) NOT NULL
	 CONSTRAINT [PK_R_DET_PRESTAMO_PENSION_REESTRUCTURADO] PRIMARY KEY CLUSTERED 
	(
		[N_CVE_PRESTAMO] ASC,
		[N_TIPO] ASC,
		[N_NO_CUOTA] ASC
	)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
	) ON [PRIMARY]
	GO
		
	CREATE NONCLUSTERED INDEX IDX_R_DET_PRESTAMO ON R_DET_PRESTAMO (N_CVE_PRESTAMO, N_TIPO, N_NO_CUOTA);
	GO

	ALTER TABLE [dbo].[R_DET_PRESTAMO] ADD  CONSTRAINT [DF_DET_PREST_N_TIPO_DET_DEFAULT_VAL] DEFAULT ((2)) FOR [N_TIPO]
	GO

	------------------------------------------------------------------------------
	CREATE TABLE [dbo].[PRESTAMO_MOISES_ROMERO](
	[N_ID_REGISTRO] [smallint] IDENTITY(1,1) NOT NULL,
	[N_CVE_PRESTAMO] [int] NOT NULL,
	[N_TIPO] [tinyint] NOT NULL,
	[DESCRIPCION] [VARCHAR](50) NULL,
 CONSTRAINT [PK_PRESTAMO_MOISES_ROMERO] PRIMARY KEY CLUSTERED 
(
[N_ID_REGISTRO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON,
ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

-------------------------------------------------------------

CREATE TABLE [dbo].[PERSONAS](
	[id] [int] NOT NULL,
	[primerNombre] [varchar](50) NOT NULL,
	[segundoNombre] [varchar](50) NULL,
	[primerApellido] [varchar](50) NOT NULL,
	[segundoApellido] [varchar](50) NULL,
PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO


